session: tgfs
mount_dir: /home/hrn/mnt/tgmount1
root:
  - source:
      chat: tgmounttestingchannel
      limit: 3000
    folders:
      - music
      - videos
  - chat: ru2chmu
    limit: 3000
    folders:
      - music
      - stickers
